name: flutter_flavor_app
description: 'Flutter example project with flavor.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.1.4
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
